GET http://localhost:3000/api/baskets

###


GET http://localhost:3000/api/baskets/BASKET005

###

DELETE http://localhost:3000/api/baskets/BASKET001

###

POST http://localhost:3000/api/baskets

###
POST http://localhost:3000/basket/BASKET009