GET http://localhost:3000/api/baskets

###


GET http://localhost:3000/api/baskets/BASKET002

###

DELETE http://localhost:3000/api/baskets/BASKET001

###

###delete request basket
DELETE  http://localhost:3000/api/baskets/BASKET001/requests



###


POST http://localhost:3000/api/baskets

###
POST https://www.satyapatel.xyz/api/baskets


### add item to request basket
POST http://localhost:3000/basket/BASKET001?hey=lol&jk=yo+yo
Content-Type: application/json

{
  "message": "hellllllooo down there!",
  "another": "hiiiii",
  "hey": {
    "there": 21
  }
}

###
POST http://localhost:3000/basket/BASKET001
Content-Type: application/json

{
  "SpyID": "Bond James"
}

###

GET http://localhost:3000/basket/BASKET001